version: '3.8'

services:
  postgres:
    container_name: postgres_swen
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - swen_db:/var/lib/postgres/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swen_db
volumes:
  swen_db: